### ISSUE TITLE
Queries can't be run against tables that contains "-"

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/moz-sql-parser#1]
Example: 

    select * from coverage-summary.source.file.covered limit 20

**Comment by klahnakoski** [comment]
>>> from moz_sql_parser import parse
    >>> import json
    >>> json.dumps(parse("select * from coverage-summary.source.file.covered limit 20"))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python27\lib\site-packages\moz_sql_parser\__init__.py", line 20, in parse
        parse_result = SQLParser.parseString(sql, parseAll=True)
      File "C:\Python27\lib\site-packages\pyparsing.py", line 1632, in parseString
        raise exc
    pyparsing.ParseException: Expected end of text (at char 22), (line:1, col:23)

**Comment by klahnakoski** [comment]
The parser response is technically correct; table names must be quoted if they contain special characters. The concern is the error is not helpful.

**Comment by klahnakoski** [comment]
https://github.com/mozilla/moz-sql-parser/commit/0a9129db1d7a7684c324c567d561c814aeb07013

    >>> from moz_sql_parser import parse
    >>> import json
    >>> json.dumps(parse("select * from coverage-summary.source.file.covered limit 20"))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python27\lib\site-packages\moz_sql_parser\__init__.py", line 32, in parse
        raise ParseException(sql, e.loc, "Expecting one of (" + (", ".join(expecting)) + ")")
    pyparsing.ParseException: Expecting one of (as, in, inner join, eq, select, end, union, when, group by, cross join, between, desc, then, else, from, with, order by, case, on, join, or, limit, collate nocase, where, having) (at char 22), (line:1, col:23)

**Comment by klahnakoski** [comment]
I think this is done.
