### ISSUE TITLE
cannot parsing a quite complex (oracle) sql statement

### ISSUE THREAD

**Issue by matteoredaelli** [mozilla/moz-sql-parser#103]
I cannot parse the following sql statement
SELECT G.ITEM_ID AS "ITEM_ID", fn_get_dimension_by_grcom (H.BU_COD, G.ITEM_ID) AS "DESCRIPTION", trim(G.EAN11) "EANCODE", trim(DECODE (G.MATNR_ORIG_B2F, NULL, DECODE (G.MATNR_ORIG, NULL, G.MATNR, G.MATNR_ORIG), G.MATNR_ORIG_B2F)) AS "CODICE_PRODOTTO", DECODE (H.BRAND, 'BF GOODRICH', 'BFGOODRICH', H.BRAND) AS "BRAND_ID", H.BRAND AS "XBRAND", H.MARKET5 AS "MKT_ID", m.MC_COUNTRY_CODE AS "COUNTRY_CODE", H.BU_COD AS "GRCOM", H.DATE_FROM AS "PRICELIST_DATE", H.CURRENCY AS "CURRENCY_ID", K.CR_DESCRIPTION AS "CURRENCY_DESC", K.CR_DESCRIPTION AS "CURRENCY_SHORT_DESC", G.PATTERN AS "BTS_ID", P.PATTERN AS "PATTERN_SHORT_DESC", trim(G.SERIES) AS "SERIE", trim(G.WIDTH) AS "CORDA", trim(G.RIM) AS "CALETTAMENTO", G.STRUTTURA AS "STRUTTURA", DECODE (IS_NUMBER (G.WIDTH), 0, 0, TO_NUMBER (G.WIDTH)) AS "CORDA_NOM", DECODE (IS_NUMBER (G.SERIES), 0, 0, TO_NUMBER (G.SERIES)) AS "SERIE_NOM", 0 AS "STRUTTURA_NOM", DECODE (IS_NUMBER (G.RIM), 0, 0, TO_NUMBER (G.RIM)) AS "CALETTAMENTO_NOM", trim(G.LOADIN1) AS "LOAD_INDEX", trim(DECODE (TRIM (G.LOADIN2), '', NULL, TRIM (G.LOADIN2))) AS "LOAD_INDEX_1", trim(G.EXTRA_LOAD_FLAG) AS "EXTRA_LOAD_INDEX", G.RUNFLAT_FLAG AS "RUNFLAT_ID", DECODE (TRIM (G.OEMARK), '', NULL, TRIM (G.OEMARK)) AS "OE_MARK", trim(G.SPEEDIN1) AS "SPEED_INDEX", trim(DECODE (TRIM (G.SPEEDIN2), '', NULL, TRIM (G.SPEEDIN2))) AS "SPEED_INDEX_1", trim(G.CODE_MKS) AS "CODE_MKS", G.DESCR_MKS AS "MKS", D.PRICE AS "GROSS_PRICE", trim(fn_get_dimension_loadindex (g.item_id)) AS "DESCR_LOADINDEX", trim(fn_get_dimension_speedindex (g.item_id)) AS "DESCR_SPEEDINDEX", DECODE (TRIM (G.LOADIN1DB), '', NULL, TRIM (G.LOADIN1DB)) AS "LOADINDEX1DOUBLEMOUNT", DECODE (TRIM (G.LOADIN2DB), '', NULL, TRIM (G.LOADIN2DB)) AS "LOADINDEX2DOUBLEMOUNT", DECODE (TRIM (G.NOISECLASS), '', NULL, TRIM (G.NOISECLASS)) AS "NOISECLASS", DECODE (G.ARTICLEGROUPCODE, '01', 'Tyre', '02', 'Rim', NULL) AS "ARTICLEGROUP", G.ARTICLEGROUPCODE AS "ARTICLEGROUPCODE", DECODE (IS_NUMBER (G.DEPTH), 1, G.DEPTH, NULL) AS "ORIGINALTREADDEPTH", DECODE (IS_NUMBER (G.WEIGHT), 1, TO_NUMBER (G.WEIGHT) * 1000, NULL) AS "WEIGHT", DECODE (g.pncs, 'Yes', 1, 'No', 0, NULL) AS "PNCS", DECODE (g.sealind, 'Yes', 1, 'No', 0, NULL) AS "SELFSEALING", DECODE (g.sealind, 'Yes', g.RUNFLAT_FLAG_SEALIND, NULL) AS "SELFSEALINGINDICATOR", DECODE (g.extra_load, 'Yes', 1, 'No', 0, NULL) AS "EXTRA_LOAD", g.application_code AS "APPLICATION_CODE", NULL AS "PRODUCTSEGMENT", DECODE (g.application_code, 'F1', 'FittedUnitCar', 'F2', 'FittedUnitVan', 'F9', 'FittedUnitSuv', '01', 'Car', '02', 'Van', '03', 'Truck', '04', 'EM', '05', 'AS', '06', 'Industry', '08', 'Moto', '09', 'SUV', NULL) AS "APPLICATION", DECODE (g.SNOWFLAG, 'Yes', 1, 'No', 0, NULL) AS "SNOWFLAG", DECODE (g.RUNFLAT, 'Yes', 1, 'No', 0, NULL) AS "RUNFLAT", DECODE (TRIM (g.NOISE_PERFORMANCE), '', NULL, TRIM (G.NOISE_PERFORMANCE)) AS "NOISE_PERFORMANCE", DECODE (TRIM (g.rollres), '', NULL, TRIM (G.rollres)) AS "ROLLRES", DECODE (TRIM (g.wetgrip), '', NULL, TRIM (G.wetgrip)) AS "WETGRIP", g.MANUFACTURER AS "MANUFACTURER", DECODE (DECODE (IS_NUMBER (g.season), 1, TO_NUMBER (g.season), 0), 1, 'summer', 2, 'winter', 10, 'allseasons', NULL) AS "SEASONALITY" FROM DIM_CURRENCY k, P2_PATTERN_ALL p, P2_MATERIAL_ALL g, DW.DIM_MARKET_CHANNEL m, PRLST_DETAIL d, (SELECT H1.PRICELIST_ID, H1.BRAND, H1.BU_COD, H1.MARKET5, H1.DATE_FROM, H1.CURRENCY FROM PRCLST_HEADER h1, LOOKUP_BRAND b1 WHERE H1.ENABLE_VIEWING_B2F = 1 AND (H1.BRAND, H1.BU_COD, H1.MARKET5, H1.DATE_FROM) IN ( SELECT H2.BRAND, H2.BU_COD, H2.MARKET5, MAX (H2.DATE_FROM) FROM PRCLST_HEADER h2 WHERE H2.BU_COD = 'CAR' AND H2.ENABLE_VIEWING_B2F = 1 GROUP BY H2.BRAND, H2.BU_COD, H2.MARKET5) AND H1.BRAND = B1.BRAND) h WHERE h.currency = K.CR_COD_CURRENCY_SAP AND h.pricelist_id = D.PRICELIST_ID AND H.BRAND = G.BRCONA AND D.IPCODE = G.MATNR AND P.BRAND = G.BRCONA AND upper(P.PATTERN) = upper(G.PATTERN) AND h.market5 = m.MARKET_CHANNEL_CODE AND G.IS_USER = 1 AND (G.BRCONA, G.MATNR) NOT IN (SELECT C.BRCONA, C.MATNR FROM P2_MAT_USER_CONFLICTS c WHERE C.LAST_ACTION IN (21)) ORDER BY G.ITEM_ID

I get

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/moz_sql_parser/__init__.py", line 53, in parse
    raise ParseException(sql, e.loc, "Expecting one of (" + (", ".join(expecting)) + ")")
pyparsing.ParseException: Expecting one of (end, div, else, when, gte, join, full join, asc, or, offset, on, neq, union, right join, union all, right outer join, cross join, then, concat, using, from, is, not between, reserved, group by, like, in, desc, lte, eq, order by, mul, nlike, inner join, full outer join, left join, left outer join, gt, nin, having, collate nocase, add, case, sub, as, limit, and, select, where, between, lt) (at char 57), (line:1, col:58)

**Comment by matteoredaelli** [comment]
There could be two bugs

1) Maybe this library cannot manage functions in queries. 

So I removed  
  fn_get_dimension_by_grcom (H.BU_COD, G.ITEM_ID) AS "DESCRIPTION"

2) but I got 

  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3871, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 5612, in parseImpl
    self.expr.tryParse(instring, loc)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1601, in tryParse
    return self._parse( instring, loc, doActions=False )[0]
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3871, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 5612, in parseImpl
    self.expr.tryParse(instring, loc)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1601, in tryParse
    return self._parse( instring, loc, doActions=False )[0]
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3871, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 5612, in parseImpl
    self.expr.tryParse(instring, loc)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1601, in tryParse
    return self._parse( instring, loc, doActions=False )[0]
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3871, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 5612, in parseImpl
    self.expr.tryParse(instring, loc)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1601, in tryParse
    return self._parse( instring, loc, doActions=False )[0]
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 3871, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1705, in _parseCache
    value = cache.get(lookup)
  File "/usr/local/lib/python3.7/dist-packages/pyparsing.py", line 1643, in get
    return cache.get(key, not_in_cache)
RecursionError: maximum recursion depth exceeded

**Comment by klahnakoski** [comment]
Whatever caused this problem, it is not a problem anymore:  https://github.com/mozilla/moz-sql-parser/pull/114
