### ISSUE TITLE
Fails to parse cast() expression

### ISSUE THREAD

**Issue by patricksurry** [mozilla/moz-sql-parser#119]
With `moz-sql-parser==3.32.20026`, simple cast expressions like `parse('select cast(3.14 as double) x')` fail.  Here's a sample stack trace:

```
>>> parse('SELECT 1 + CAST(1 AS INT) result')
Traceback (most recent call last):
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/moz_sql_parser/__init__.py", line 43, in parse
    parse_result = SQLParser.parseString(sql, parseAll=True)
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/pyparsing.py", line 1814, in parseString
    raise exc
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/pyparsing.py", line 1808, in parseString
    se._parse( instring, loc )
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/pyparsing.py", line 3722, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/pyparsing.py", line 1552, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/pyparsing.py", line 3502, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text (at char 15), (line:1, col:16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/psurry/miniconda3/envs/samarkand/lib/python3.8/site-packages/moz_sql_parser/__init__.py", line 53, in parse
    raise ParseException(sql, e.loc, "Expecting one of (" + (", ".join(expecting)) + ")")
pyparsing.ParseException: Expecting one of (order by, in, cross join, then, case, like, full join, union, concat, neq, on, with, as, is, and, collate nocase, end, binary_and, full outer join, where, asc, nin, or, nlike, between, not_between, when, offset, inner join, left outer join, using, select, limit, having, reserved, group by, right outer join, else, union all, binary_or, desc, left join, join, from, right join) (at char 15), (line:1, col:16)
>>> 
```

**Comment by kabirsachdev** [comment]
Facing the same issue when trying to use CAST function in the query parser
Can you please look into this @klahnakoski 
Thanks

**Comment by klahnakoski** [comment]
I will add a couple of tests and fix that this weekend

**Comment by avishalom** [comment]
also happens for shorthand cast expressions e.g. `::int`

**Comment by klahnakoski** [comment]
turns out solving this is hard:  The pyparsing library needs some optimization before we can move on this:  https://github.com/mozilla/moz-sql-parser/blob/dev/docs/Student%20Project%202019.md#the-pyparsing-infixnotation-is-busted

**Comment by klahnakoski** [comment]
first version is here: https://github.com/klahnakoski/moz-sql-parser/commit/8033f06abcc796fd4952063311938ee2b0888a05#diff-61d5a1a018e97cc478eba974e6abfff036bf58e449578b7b680fab7f2e63976dR1065
