### ISSUE TITLE
Error when using alias on the FROM

### ISSUE THREAD

**Issue by DavidHernandez** [mozilla/moz-sql-parser#121]
We have tried to parse the next SQL  `SELECT s.a FROM generate_series(1,2) AS s(a)` and got the next error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/moz_sql_parser/__init__.py", line 43, in parse
    parse_result = SQLParser.parseString(sql, parseAll=True)
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 1216, in parseString
    raise exc
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 1210, in parseString
    se._parse( instring, loc )
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 1072, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 2544, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 1137, in _parseCache
    value = self._parseNoCache( instring, loc, doActions, callPreParse )
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 1076, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.7/site-packages/pyparsing.py", line 2347, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text (at char 22), (line:1, col:23)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/moz_sql_parser/__init__.py", line 53, in parse
    raise ParseException(sql, e.loc, "Expecting one of (" + (", ".join(expecting)) + ")")
pyparsing.ParseException: Expecting one of (join, right join, union, group by, full join, having, inner join, where, left join, right outer join, limit, left outer join, ord
er by, full outer join, offset) (at char 22), (line:1, col:23)
```

## Steps to reproduce

`$ python`
`>>> from moz_sql_parser import parse`
`>>> sql = 'SELECT s.a FROM generate_series(1,2) AS s(a)'`
`>>> parse(sql)`

**Comment by DavidHernandez** [comment]
I've added a PR with a test to prove that this is failing: https://github.com/mozilla/moz-sql-parser/pull/122

I am not sure if this syntax is from the SQL-92 specification or not.

**Comment by klahnakoski** [comment]
fixed here https://github.com/klahnakoski/moz-sql-parser/commit/438d1ac490b149f883134390da52a82487329668#diff-5cdc87095af9dc76d067a08b883f9043c4d778ba719ddc61ec945520d0a73a1bR1846
