### ISSUE TITLE
Unable to parse Oracle DB Create table schema

### ISSUE THREAD

**Issue by SakibFarhad** [mozilla/moz-sql-parser#124]
I have been trying to parse a Create Table Schema as following
```sql
CREATE TABLE warehouses
  (
    warehouse_id NUMBER 
                 GENERATED BY DEFAULT AS IDENTITY START WITH 10 
                 PRIMARY KEY,
    warehouse_name VARCHAR( 255 ) ,
    location_id    NUMBER( 12, 0 ),
    CONSTRAINT fk_warehouses_locations 
      FOREIGN KEY( location_id )
      REFERENCES locations( location_id ) 
      ON DELETE CASCADE
  );
```
## Environment:  
* python==3.7 
* moz-sql-parser==3.32.20026 

## Source:
```python
sql = '''
CREATE TABLE warehouses
  (
    warehouse_id NUMBER 
                 GENERATED BY DEFAULT AS IDENTITY START WITH 10 
                 PRIMARY KEY,
    warehouse_name VARCHAR( 255 ) ,
    location_id    NUMBER( 12, 0 ), -- fk
    CONSTRAINT fk_warehouses_locations 
      FOREIGN KEY( location_id )
      REFERENCES locations( location_id ) 
      ON DELETE CASCADE
  );
'''
from moz_sql_parser import parse
import json 

print (json.dumps(parse(sql)))
```

## Error:
```bash
Traceback (most recent call last):
File "extra/sql_parser.py", line 19, in <module>
print (json.dumps(parse(sql)))
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/moz_sql_parser/__init__.py", line 43, in parse
parse_result = SQLParser.parseString(sql, parseAll=True)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1814, in parseString
raise exc
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1804, in parseString
loc, tokens = self._parse( instring, 0 )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 4067, in parseImpl
return self.expr._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 3722, in parseImpl
loc, exprtokens = e._parse( instring, loc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 4067, in parseImpl
return self.expr._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 4067, in parseImpl
return self.expr._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 3705, in parseImpl
loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 4067, in parseImpl
return self.expr._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 4067, in parseImpl
return self.expr._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 3705, in parseImpl
loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 4067, in parseImpl
return self.expr._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1548, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 3705, in parseImpl
loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1530, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 4067, in parseImpl
return self.expr._parse( instring, loc, doActions, callPreParse=False )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1709, in _parseCache
value = self._parseNoCache(instring, loc, doActions, callPreParse)
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 1530, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/home/sakib/Projects/project-crossroad/env/lib/python3.7/site-packages/pyparsing.py", line 2689, in parseImpl
raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected select (at char 1), (line:2, col:1)
```

What am I missing here.

**Comment by kapilt** [comment]
the readme states its not for inserts, deletes, its primarily oriented to selects, not generic sqlparsing (sqlparse lib may be more appropriate for those use cases).
