### ISSUE TITLE
Using clause not supported

### ISSUE THREAD

**Issue by victoriabeldo** [mozilla/moz-sql-parser#127]
There exists a clause called _using_ that can ease the query writing:
https://lornajane.net/posts/2012/sql-joins-with-on-or-using
If we write the following query:
**select owners.name, pets.name, pets.animal from owners join pets on (pets.owners_id = owners.owners_id)**, 
as both tables have the same column name we could just write : 
**select owners.name as owner, pets.name as pet, pets.animal from owners join pets using (owners_id)**

If you try to execute this on the moz_sql_parser,it returns the following:
>from moz_sql_parser import format, parse
>format(parse('select owners.name as owner, pets.name as pet, pets.animal from owners join pets using (owners_id)'))
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/victoria/.local/lib/python3.6/site-packages/moz_sql_parser/__init__.py", line 59, in format
    return Formatter(**kwargs).format(json)
  File "/home/victoria/.local/lib/python3.6/site-packages/moz_sql_parser/formatting.py", line 153, in format
    return self.query(json)
  File "/home/victoria/.local/lib/python3.6/site-packages/moz_sql_parser/formatting.py", line 293, in query
    for clause in self.clauses
  File "/home/victoria/.local/lib/python3.6/site-packages/moz_sql_parser/formatting.py", line 294, in <genexpr>
    for part in [getattr(self, clause)(json)]
  File "/home/victoria/.local/lib/python3.6/site-packages/moz_sql_parser/formatting.py", line 315, in from_
    parts.append(self.dispatch(token))
  File "/home/victoria/.local/lib/python3.6/site-packages/moz_sql_parser/formatting.py", line 170, in dispatch
    return self.op(json)
  File "/home/victoria/.local/lib/python3.6/site-packages/moz_sql_parser/formatting.py", line 190, in op
    raise Exception('Operators should have only one key!')
Exception: Operators should have only one key!

**Comment by klahnakoski** [comment]
this is now fixed
