### ISSUE TITLE
(py)parser enters infinite recursion loop with WHERE clause enclosed with parenthesis

### ISSUE THREAD

**Issue by dforsber** [mozilla/moz-sql-parser#144]
# (py)parser enters infinite recursion loop with WHERE clause enclosed with parenthesis

Please find below the SELECT clause that causes parser to enter infinite recursion loop and eventually cause Python to crash.

`SELECT count(url) FROM crawl_urls WHERE ((http_status_code = 200 AND meta_redirect = FALSE AND primary_page = TRUE AND indexable = TRUE AND canonicalized_page = FALSE AND (paginated_page = FALSE OR (paginated_page = TRUE AND page_1 = TRUE))) AND ((css <> TRUE AND js <> TRUE AND is_image <> TRUE AND internal = TRUE) AND (header_content_type = 'text/html' OR header_content_type = ''))) ORDER BY count(url) DESC`

Running in AWS Lambda Python38.

This maybe a bug in **pyparsing** library as it seems, but would be good to add similar test case into this module as well?

==> **If you remove the outermost parenthesis from the WHERE clause, the query seems to work.**

The trace back:

```
[ERROR] RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/var/task/handler.py", line 225, in handle
    results = {k: runDuckdbFromEfsParquet(
  File "/var/task/handler.py", line 225, in <dictcomp>
    results = {k: runDuckdbFromEfsParquet(
  File "/var/task/handler.py", line 186, in runDuckdbFromEfsParquet
    query = getSQL(metric.pop('sql'), crawlId, rows)
  File "/var/task/handler.py", line 171, in getSQL
    query = replaceTableName(query, crawlId)
  File "/var/task/handler.py", line 154, in replaceTableName
    parsed = parse(query)
  File "/var/task/moz_sql_parser/__init__.py", line 43, in parse
    parse_result = SQLParser.parseString(sql, parseAll=True)
  File "/var/task/pyparsing.py", line 1804, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/var/task/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/var/task/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/var/task/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/var/task/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/var/task/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/var/task/pyparsing.py", line 3722, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/var/task/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/var/task/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/var/task/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/var/task/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/var/task/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/var/task/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/var/task/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/var/task/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/var/task/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/var/task/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/var/task/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/var/task/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/var/task/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/var/task/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/var/task/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/var/task/pyparsing.py", line 1709, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/var/task/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/var/task/pyparsing.py", line 3705, in parseImpl

<continues forever until max recursion reached>
...
```

**Comment by klahnakoski** [comment]
made test.  and fixed https://github.com/klahnakoski/moz-sql-parser/commit/0643e5a6d148d9ffd1fc8bdecf14c1c1aaa5a2f6#diff-61d5a1a018e97cc478eba974e6abfff036bf58e449578b7b680fab7f2e63976dR966

**Comment by klahnakoski** [comment]
@dforsber   please close this issue.  I am unable to.  thank you
