### ISSUE TITLE
Can't run just 'select_one_column' unit test

### ISSUE THREAD

**Issue by tolmanam** [mozilla/moz-sql-parser#21]
The unit tests all pass when you run them all, but weird things happen if I try to run just the 'select_one_column' test.
```
$ python -m unittest tests.test_simple.TestSimple -f
...................s............
----------------------------------------------------------------------
Ran 32 tests in 2.076s

OK (skipped=1)
```

```
$ python -m unittest tests.test_simple.TestSimple.select_one_column -f
2018-09-12 13:13:44 - WARNING: Can not expand expected|json|limit(10000) in template: "ERROR: {{test|json|limit(10000)}} does not match expected {{expected|json|limit(10000)}}\n"
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/strings.py", line 657, in replacer
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/strings.py", line 661, in _simple_expand
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/strings.py", line 534, in expand_template
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/exceptions.py", line 108, in __unicode__
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/exceptions.py", line 125, in __str__
        File "/yourusername/anaconda3/lib/python3.6/traceback.py", line 151, in _some_str
        File "/yourusername/anaconda3/lib/python3.6/traceback.py", line 501, in __init__
        File "/yourusername/anaconda3/lib/python3.6/traceback.py", line 486, in __init__
        File "/yourusername/anaconda3/lib/python3.6/traceback.py", line 486, in __init__
        File "/yourusername/anaconda3/lib/python3.6/unittest/result.py", line 186, in _exc_info_to_string
        File "/yourusername/anaconda3/lib/python3.6/unittest/result.py", line 115, in addError
        File "/yourusername/anaconda3/lib/python3.6/unittest/result.py", line 17, in inner
        File "/yourusername/anaconda3/lib/python3.6/unittest/runner.py", line 67, in addError
        File "/yourusername/anaconda3/lib/python3.6/unittest/case.py", line 543, in _feedErrorsToResult
        File "/yourusername/anaconda3/lib/python3.6/unittest/case.py", line 613, in run
        File "/yourusername/anaconda3/lib/python3.6/unittest/case.py", line 653, in __call__
        File "/yourusername/anaconda3/lib/python3.6/unittest/suite.py", line 122, in run
        File "/yourusername/anaconda3/lib/python3.6/unittest/suite.py", line 84, in __call__
        File "/yourusername/anaconda3/lib/python3.6/unittest/suite.py", line 122, in run
        File "/yourusername/anaconda3/lib/python3.6/unittest/suite.py", line 84, in __call__
        File "/yourusername/anaconda3/lib/python3.6/unittest/runner.py", line 176, in run
        File "/yourusername/anaconda3/lib/python3.6/unittest/main.py", line 256, in runTests
        File "/yourusername/anaconda3/lib/python3.6/unittest/main.py", line 95, in __init__
        File "/yourusername/anaconda3/lib/python3.6/unittest/__main__.py", line 18, in <module>
        File "/yourusername/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
        File "/yourusername/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
caused by
        ERROR: Object of type 'Data' is not JSON serializable
        File "/yourusername/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
        File "/yourusername/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
        File "/yourusername/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
        File "/yourusername/anaconda3/lib/python3.6/json/__init__.py", line 231, in dumps
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/strings.py", line 48, in <lambda>
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/strings.py", line 184, in json
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/strings.py", line 638, in replacer
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/strings.py", line 661, in _simple_expand
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/strings.py", line 534, in expand_template
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/exceptions.py", line 108, in __unicode__
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/exceptions.py", line 125, in __str__
        File "/yourusername/anaconda3/lib/python3.6/traceback.py", line 151, in _some_str
.
.
<snip>
.
.
        File "/yourusername/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main

E
======================================================================
ERROR: select_one_column (tests.test_simple.TestSimple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/yourusername/sandbox/moz-sql-parser/tests/test_simple.py", line 46, in select_one_column
    self.assertEqual(result, expected)
  File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_testing/fuzzytestcase.py", line 57, in assertEqual
    self.assertAlmostEqual(test_value, expected, msg=msg, digits=digits, places=places, delta=delta)
  File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_testing/fuzzytestcase.py", line 54, in assertAlmostEqual
    assertAlmostEqual(test_value, expected, msg=msg, digits=digits, places=coalesce(places, self.default_places), delta=delta)
  File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_testing/fuzzytestcase.py", line 140, in assertAlmostEqual
    cause=e
  File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_logs/__init__.py", line 415, in error
    raise_from_none(e)
  File "<string>", line 2, in raise_from_none
mo_logs.exceptions.Except: ERROR: [template expansion error: (Object of type 'Data' is not JSON serializable)] does not match expected [template expansion error: (Object of type 'Data' is not JSON serializable)]
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_testing/fuzzytestcase.py", line 140, in assertAlmostEqual
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_testing/fuzzytestcase.py", line 54, in assertAlmostEqual
        File "/yourusername/sandbox/moz-sql-parser/venv/lib/python3.6/site-packages/mo_testing/fuzzytestcase.py", line 57, in assertEqual
        File "/yourusername/sandbox/moz-sql-parser/tests/test_simple.py", line 46, in select_one_column
        File "/yourusername/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
.
.
<snip>
.
.
----------------------------------------------------------------------
Ran 1 test in 0.039s

FAILED (errors=1)

```

**Comment by tolmanam** [comment]
The "error" also happens if you run just the 'select_many_column' test.

**Comment by klahnakoski** [comment]
There appears to be two problems.  The first one is that the test did not start with "test", so it never ran; that is fixed by the PR.

The second problem is logging the error failed.  Be sure to

    pip install -r tests/requirements.txt

so the tests run smoother, even if they fail.

**Comment by klahnakoski** [comment]
added another "test" prefix:

https://github.com/mozilla/moz-sql-parser/commit/a1e502200839a66bd3315b181daf3e1d68492166

**Comment by betodealmeida** [comment]
@tolmanam I just created https://github.com/mozilla/moz-sql-parser/pull/23 doing the SQL generation, I didn't know you were working on it.
